scan:
  regex: ^.*.\.yaml
  ignore:
    regexes:
      - .*composite.*

exampleProject: crossplane/crossplane@v0.10.0

tokenVariables:
  "gitlab.intern": TOKEN 

repositoryConfigFile: sopdocs-config.yaml