---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sopdocs.fullname" . }}-configfile
data:
  doc-config.yaml: {{- .Values.config | toYaml | indent 1 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sopdocs.fullname" . }}-schema
data:
{{ (.Files.Glob "schema/crds_up.sql").AsConfig | indent 2 }}