---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sopdocs.fullname" . }}-config
data:
  PG_USER: {{ .Values.env.PG_USER | b64enc }}
  PG_PASS: {{ .Values.env.PG_PASS | b64enc }}
  TOKEN: {{ .Values.env.TOKEN | b64enc | quote }}