apiVersion: v1
kind: Service
metadata:
  name: {{ include "sopdocs.fullname" . }}
  labels:
    {{- include "sopdocs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5050
      protocol: TCP
      name: http
  selector:
    {{- include "sopdocs.selectorLabels" . | nindent 4 }}
