name: build docker images
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}
      -
        name: Build and push doc
        uses: docker/build-push-action@v3
        with:
          file: deploy/doc.Dockerfile
          push: true
          tags: sopdocs/doc:latest
      -
        name: Build and push gitter
        uses: docker/build-push-action@v3
        with:
          file: deploy/gitter.Dockerfile
          push: true
          tags: sopdocs/gitter:latest